name: LaTeX PDF Generation

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install LaTeX
      run: sudo apt-get install texlive-xetex texlive-fonts-recommended texlive-fonts-extra

    - name: Compile LaTeX document
      run: xelatex -interaction=nonstopmode -halt-on-error -jobname=Priyanshu_Lanjewar resume.tex

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v2
      with:
        name: generated-pdf
        path: Priyanshu_Lanjewar.pdf
