name: LaTeX PDF Generation

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # - name: Install LaTeX
    #   run: sudo apt-get install texlive-xetex texlive-fonts-recommended texlive-fonts-extra

    # - name: Compile LaTeX document
    #   run: xelatex -interaction=nonstopmode -halt-on-error -jobname=Priyanshu_Lanjewar resume.tex

    # - name: Upload PDF artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: generated-pdf
    #     path: Priyanshu_Lanjewar.pdf

    # - name: Create release
    #   id: create_release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
    #   with:
    #     tag_name: ${{ github.ref }}
    #     release_name: Release ${{ github.ref }}
    #     body: |
    #       Release ${{ github.ref }}
    #     draft: false
    #     prerelease: false

    # - name: Upload PDF to release
    #   id: upload-release-asset
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: Priyanshu_Lanjewar.pdf
    #     asset_name: Priyanshu_Lanjewar.pdf
    #     asset_content_type: application/pdf

    - name: Fetch latest release information from first repository
      id: fetch-latest-release
      run: |
        response=$(curl -sH "Authorization: token ${{ secrets.PAT_TOKEN }}" \
                      "https://api.github.com/repos/priyanshu-lanjewar/resume/releases/latest")
        DOWNLOAD_URL=$(echo "$response" | jq -r '.assets[0].browser_download_url')
        echo "::set-output name=url::$DOWNLOAD_URL"
    
    - name: Update file in second repository
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Update file with PDF URL"
        title: "Update file with PDF URL"
        body: "Updating file with the PDF URL obtained from latest release of first repository."
        branch: update-pdf-url
        branch-suffix: timestamp
        base: main
        files: |
          https://github.com/priyanshu-lanjewar/priyanshu-lanjewar.github.io/assets/js/submit.js:${{ steps.fetch_latest_release.outputs.url }}
