name: LaTeX PDF Generation

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install LaTeX
      run: sudo apt-get install texlive-xetex texlive-fonts-recommended texlive-fonts-extra

    - name: Compile LaTeX document
      run: xelatex -interaction=nonstopmode -halt-on-error -jobname=Priyanshu_Lanjewar resume.tex

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v2
      with:
        name: generated-pdf
        path: Priyanshu_Lanjewar.pdf

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload PDF to release
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: Priyanshu_Lanjewar.pdf
        asset_name: Priyanshu_Lanjewar.pdf
        asset_content_type: application/pdf
